[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/*.(js|css|png|jpg|jpeg|gif|svg)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

